# Generated by Django 4.0.3 on 2022-03-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('meeting_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('meeting_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('number', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('seating_capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('numb_of_students', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routineGen.instructor')),
            ],
        ),
    ]
