# Generated by Django 4.0.3 on 2022-03-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routineGen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['instructor_id']},
        ),
        migrations.AlterModelOptions(
            name='meetingtime',
            options={'ordering': ['meeting_id'], 'verbose_name': 'Meeting Time'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['number']},
        ),
    ]
