# Generated by Django 4.0.3 on 2022-03-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routineGen', '0002_alter_course_options_alter_instructor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meetingtime',
            table='MeetingTime',
        ),
    ]
