# Generated by Django 4.0.3 on 2022-03-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routineGen', '0003_alter_meetingtime_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meetingtime',
            table='meetingtime',
        ),
    ]
