# Generated by Django 4.0.3 on 2022-03-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routineGen', '0004_alter_meetingtime_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingTime',
        ),
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='numb_of_students',
            field=models.IntegerField(),
        ),
    ]
