# Generated by Django 4.0.3 on 2022-03-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routineGen', '0006_meetingtime_alter_room_seating_capacity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingTime',
        ),
    ]
