# Generated by Django 4.0.3 on 2022-03-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routineGen', '0007_delete_meetingtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('meeting_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('meeting_day', models.CharField(max_length=11)),
                ('meeting_start_time', models.TimeField()),
                ('meeting_end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Meeting Time',
                'db_table': 'meetingtime',
            },
        ),
    ]
